### ISSUE TITLE
Looks awesome but perhaps consider using name `Merkle::Tree`

### ISSUE THREAD

**Issue by ioquatix** [piotrmurach/merkle_tree#1]
Would naturally fit with `Merkle::Node`. I wonder if it's slightly nicer to type out/shorter. Gem is also available on RubyGems.

**Comment by ioquatix** [comment]
Feel free to close this issue if you think it's irrelevant. Anyway, nice work, looks interesting, I will definitely try it out in the future.

**Comment by piotrmurach** [comment]
There is already [splay_tree](https://github.com/piotrmurach/splay_tree) which I've implemented some time ago and I like to keep the "tradition". I do also prefer `MerkleTree::Node`, `MerkleTree::Leaf`.

**Comment by ioquatix** [comment]
That makes sense.

**Comment by piotrmurach** [comment]
That is some record breaking issue. I've never had anyone open and close one so quick 💨 after public release 😉
